spring:
  application:
    name: security-security
  datasource:
    url: jdbc:postgresql://localhost:8281/otus
    password: otus
    username: otus
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
logging:
  level:
    root: INFO
    com.mypackage: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log